### ISSUE TITLE
1.1.0 is broken?

### ISSUE THREAD

**Issue by errogaht** [wapmorgan/FileTypeDetector#2]
Hello, im using 1.0.5
but in composer i have ^1.0
and yesterday when you push new 1.1.0 tag - tests on my package not passing, because your package have issues.
first to gen mime im using `implode('/', $result)` and in 1.0.5 is work = `image/png` but in 1.1.0 result is `image/png/image/png`

and https://github.com/wapmorgan/FileTypeDetector/blob/master/src/Detector.php#L561 `$file` is undefined

**Comment by wapmorgan** [comment]
Thanks for fb! Firstly result of implod'ing array is expected as detect*() functions now returns array with 3 elements, in which 3rd is a Mimetype for given file. 
Secondly yes, there is a typo, leading to bug. Thanks, will be fixed soon.

**Comment by wapmorgan** [comment]
Ok, I've fixed bugs. Try **1.1.1** version!

**Comment by wapmorgan** [comment]
For your case use `getMimeType($file)` function.
